// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: coreum/feemodel/v1/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params stores parameters defining fee model of coreum blockchain
// There are four regions on the fee model curve
// - between 0 and "long average block gas" where gas price goes down exponentially from InitialGasPrice to gas price with maximum discount (InitialGasPrice * (1 -MaxDiscount))
// - between "long average block gas" and EscalationStartBlockGas where we offer gas price with maximum discount all the time
// - between EscalationStartBlockGas and MaxBlockGas where price goes up rapidly (being an output of a power function) from gas price with maximum discount to MaxGasPrice
// - above MaxBlockGas (if it happens for any reason) where price is equal to MaxGasPrice
//
// The input (x value) for that function is calculated by taking short block gas average.
// Price (y value) being an output of the fee model is used as the minimum gas price for next block.
type Params struct {
	// initial_gas_price is used when block gas short average is 0. It happens when there are no transactions being broadcasted. This value is also used to initialize gas price on brand-new chain.
	InitialGasPrice github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=initial_gas_price,json=initialGasPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"initial_gas_price" yaml:"initial_gas_price"`
	// max_gas_price is used when block gas short average is greater than or equal to MaxBlockGas. This value is used to limit gas price escalation to avoid having possible infinity GasPrice value otherwise.
	MaxGasPrice github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=max_gas_price,json=maxGasPrice,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_gas_price" yaml:"max_gas_price"`
	// max_discount is th maximum discount we offer on top of initial gas price if short average block gas is between long average block gas and escalation start block gas.
	MaxDiscount github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=max_discount,json=maxDiscount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_discount" yaml:"max_discount"`
	// escalation_start_block_gas defines block gas usage where gas price escalation starts if short average block gas is higher than this value.
	EscalationStartBlockGas int64 `protobuf:"varint,4,opt,name=escalation_start_block_gas,json=escalationStartBlockGas,proto3" json:"escalation_start_block_gas,omitempty" yaml:"escalation_start_block_gas"`
	// max_block_gas sets the maximum capacity of block. This is enforced on tendermint level in genesis configuration. Once short average block gas goes above this value, gas price is a flat line equal to MaxGasPrice.
	MaxBlockGas int64 `protobuf:"varint,5,opt,name=max_block_gas,json=maxBlockGas,proto3" json:"max_block_gas,omitempty" yaml:"max_block_gas"`
	// short_ema_block_length defines inertia for short average long gas in EMA model. The equation is: NewAverage = ((ShortAverageBlockLength - 1)*PreviousAverage + GasUsedByCurrentBlock) / ShortAverageBlockLength
	// The value might be interpreted as the number of blocks which are taken to calculate the average. It would be exactly like that in SMA model, in EMA this is an approximation.
	ShortEmaBlockLength uint32 `protobuf:"varint,6,opt,name=short_ema_block_length,json=shortEmaBlockLength,proto3" json:"short_ema_block_length,omitempty" yaml:"short_ema_block_length"`
	// long_ema_block_length defines inertia for long average block gas in EMA model. The equation is: NewAverage = ((LongAverageBlockLength - 1)*PreviousAverage + GasUsedByCurrentBlock) / LongAverageBlockLength
	// The value might be interpreted as the number of blocks which are taken to calculate the average. It would be exactly like that in SMA model, in EMA this is an approximation.
	LongEmaBlockLength uint32 `protobuf:"varint,7,opt,name=long_ema_block_length,json=longEmaBlockLength,proto3" json:"long_ema_block_length,omitempty" yaml:"long_ema_block_length"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3500559e6fedefd6, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEscalationStartBlockGas() int64 {
	if m != nil {
		return m.EscalationStartBlockGas
	}
	return 0
}

func (m *Params) GetMaxBlockGas() int64 {
	if m != nil {
		return m.MaxBlockGas
	}
	return 0
}

func (m *Params) GetShortEmaBlockLength() uint32 {
	if m != nil {
		return m.ShortEmaBlockLength
	}
	return 0
}

func (m *Params) GetLongEmaBlockLength() uint32 {
	if m != nil {
		return m.LongEmaBlockLength
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "coreum.feemodel.v1.Params")
}

func init() { proto.RegisterFile("coreum/feemodel/v1/params.proto", fileDescriptor_3500559e6fedefd6) }

var fileDescriptor_3500559e6fedefd6 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x13, 0xb6, 0x15, 0x61, 0x98, 0x10, 0xde, 0x80, 0x50, 0x41, 0xdc, 0x45, 0x02, 0xf5,
	0x42, 0xa2, 0x69, 0xb7, 0x89, 0x53, 0xd8, 0x1f, 0x09, 0x81, 0x34, 0x65, 0x12, 0x07, 0x2e, 0x91,
	0xeb, 0x9a, 0x24, 0x2c, 0x8e, 0xab, 0xd8, 0xa9, 0xba, 0x6f, 0xc1, 0x91, 0x23, 0x77, 0xbe, 0xc8,
	0x8e, 0x3b, 0x22, 0x0e, 0x11, 0x6a, 0xbf, 0x41, 0x3e, 0x01, 0xb2, 0x9d, 0x2d, 0xad, 0x36, 0x0e,
	0x3b, 0xb5, 0x7e, 0x9e, 0x27, 0xbf, 0xc7, 0x7a, 0xad, 0x17, 0x20, 0xc2, 0x4b, 0x5a, 0xb1, 0xe0,
	0x2b, 0xa5, 0x8c, 0x8f, 0x69, 0x1e, 0x4c, 0x77, 0x83, 0x09, 0x2e, 0x31, 0x13, 0xfe, 0xa4, 0xe4,
	0x92, 0x43, 0x68, 0x02, 0xfe, 0x55, 0xc0, 0x9f, 0xee, 0xf6, 0x5f, 0x10, 0x2e, 0x18, 0x17, 0xb1,
	0x4e, 0x04, 0xe6, 0x60, 0xe2, 0xfd, 0xed, 0x84, 0x27, 0xdc, 0xe8, 0xea, 0x9f, 0x51, 0xbd, 0x5f,
	0x1b, 0xa0, 0x77, 0xa2, 0xa9, 0x70, 0x0a, 0x9e, 0x64, 0x45, 0x26, 0x33, 0x9c, 0xc7, 0x09, 0x56,
	0x88, 0x8c, 0x50, 0xc7, 0x1e, 0xd8, 0xc3, 0x07, 0xe1, 0x87, 0x8b, 0x1a, 0x59, 0x7f, 0x6a, 0xf4,
	0x26, 0xc9, 0x64, 0x5a, 0x8d, 0x7c, 0xc2, 0x59, 0x0b, 0x6f, 0x7f, 0xde, 0x8a, 0xf1, 0x59, 0x20,
	0xcf, 0x27, 0x54, 0xf8, 0x07, 0x94, 0x34, 0x35, 0x72, 0xce, 0x31, 0xcb, 0xf7, 0xbd, 0x1b, 0x40,
	0x2f, 0x7a, 0xdc, 0x6a, 0xc7, 0x58, 0x9c, 0x28, 0x05, 0x7e, 0x03, 0x9b, 0x0c, 0xcf, 0x96, 0x3a,
	0xef, 0xe9, 0xce, 0xa3, 0x3b, 0x77, 0x6e, 0x9b, 0xce, 0x15, 0x98, 0x17, 0x3d, 0x64, 0x78, 0x76,
	0xdd, 0x95, 0x82, 0x47, 0xca, 0x1e, 0x67, 0x82, 0xf0, 0xaa, 0x90, 0xce, 0x9a, 0xae, 0x3a, 0xbc,
	0x73, 0xd5, 0x56, 0x57, 0x75, 0xc5, 0x32, 0x4d, 0x07, 0xed, 0x09, 0x8e, 0x40, 0x9f, 0x0a, 0x82,
	0x73, 0x2c, 0x33, 0x5e, 0xc4, 0x42, 0xe2, 0x52, 0xc6, 0xa3, 0x9c, 0x93, 0x33, 0x75, 0x37, 0x67,
	0x7d, 0x60, 0x0f, 0xd7, 0xc2, 0xd7, 0x4d, 0x8d, 0x76, 0x0c, 0xe9, 0xff, 0x59, 0x2f, 0x7a, 0xde,
	0x99, 0xa7, 0xca, 0x0b, 0x95, 0x75, 0x8c, 0x05, 0x7c, 0x67, 0x26, 0xd7, 0x61, 0x37, 0x34, 0xd6,
	0x59, 0x9d, 0xc5, 0x12, 0x49, 0xdd, 0xf0, 0xfa, 0xeb, 0xcf, 0xe0, 0x99, 0x48, 0x79, 0x29, 0x63,
	0xca, 0x70, 0x1b, 0xca, 0x69, 0x91, 0xc8, 0xd4, 0xe9, 0x0d, 0xec, 0xe1, 0x66, 0xb8, 0xd3, 0xd4,
	0xe8, 0x95, 0xc1, 0xdc, 0x9e, 0xf3, 0xa2, 0x2d, 0x6d, 0x1c, 0x32, 0xac, 0xa1, 0x1f, 0xb5, 0x0a,
	0x4f, 0xc1, 0xd3, 0x9c, 0x17, 0xc9, 0x4d, 0xec, 0x7d, 0x8d, 0x1d, 0x34, 0x35, 0x7a, 0x69, 0xb0,
	0xb7, 0xc6, 0xbc, 0x08, 0x2a, 0x7d, 0x15, 0xba, 0xbf, 0xfe, 0xe3, 0x27, 0xb2, 0xc2, 0x4f, 0x17,
	0x73, 0xd7, 0xbe, 0x9c, 0xbb, 0xf6, 0xdf, 0xb9, 0x6b, 0x7f, 0x5f, 0xb8, 0xd6, 0xe5, 0xc2, 0xb5,
	0x7e, 0x2f, 0x5c, 0xeb, 0xcb, 0xde, 0xd2, 0xd3, 0xbd, 0xd7, 0x7b, 0x71, 0xc4, 0xab, 0x62, 0xac,
	0x87, 0x16, 0xb4, 0x9b, 0x34, 0xeb, 0x76, 0x49, 0xbf, 0xe5, 0xa8, 0xa7, 0x77, 0x60, 0xef, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x52, 0xfe, 0x7f, 0x6b, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LongEmaBlockLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.LongEmaBlockLength))
		i--
		dAtA[i] = 0x38
	}
	if m.ShortEmaBlockLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ShortEmaBlockLength))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxBlockGas != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxBlockGas))
		i--
		dAtA[i] = 0x28
	}
	if m.EscalationStartBlockGas != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EscalationStartBlockGas))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.MaxDiscount.Size()
		i -= size
		if _, err := m.MaxDiscount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MaxGasPrice.Size()
		i -= size
		if _, err := m.MaxGasPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.InitialGasPrice.Size()
		i -= size
		if _, err := m.InitialGasPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.InitialGasPrice.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxGasPrice.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxDiscount.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.EscalationStartBlockGas != 0 {
		n += 1 + sovParams(uint64(m.EscalationStartBlockGas))
	}
	if m.MaxBlockGas != 0 {
		n += 1 + sovParams(uint64(m.MaxBlockGas))
	}
	if m.ShortEmaBlockLength != 0 {
		n += 1 + sovParams(uint64(m.ShortEmaBlockLength))
	}
	if m.LongEmaBlockLength != 0 {
		n += 1 + sovParams(uint64(m.LongEmaBlockLength))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialGasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxGasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDiscount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxDiscount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscalationStartBlockGas", wireType)
			}
			m.EscalationStartBlockGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EscalationStartBlockGas |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBlockGas", wireType)
			}
			m.MaxBlockGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBlockGas |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShortEmaBlockLength", wireType)
			}
			m.ShortEmaBlockLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShortEmaBlockLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LongEmaBlockLength", wireType)
			}
			m.LongEmaBlockLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LongEmaBlockLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
