chain:
  bech32_prefix: {{ .Cored.AddressPrefix }}
  modules:
    # cosmos modules
    - modules
    # - auth
    - bank
    - staking
    - consensus
    # - mint
    # - distribution
    # - pricefeed
    # - gov
    # - slashing
    # - messages    # listed as available but unsure
    - actions       # from hasura

node:
  type: remote
  config:
    rpc:
      client_name: juno
      address: http://{{ .Cored.Host }}:{{ .Cored.PortRPC }}
      max_connections: 20
    grpc:
      address: {{ .Cored.Host }}:{{ .Cored.PortGRPC }}
      insecure: true

parsing:
  workers: 1
  listen_new_blocks: true
  parse_old_blocks: true
  parse_genesis: true
  start_height: 1
  average_block_time: 1.5s

database:
  name: {{ .Postgres.DB }}
  host: {{ .Postgres.Host }}
  port: {{ .Postgres.Port }}
  user: {{ .Postgres.User }}
  schema: public
  max_open_connections: 1
  max_idle_connections: 1
  partition_size: 100000
  partition_batch: 1000

logging:
  level: debug
  format: text

actions:
  port: {{ .Port }}
