name: Bug Report
description: Report a bug encountered while using coreum ecosystem (cored, crust etc)
labels: []
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Please provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner.
        If this matter is security related, please disclose it privately via [email](mailto:hello@coreum.com)
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce the behavior (as precisely as possible)
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Versions (please complete the following information)
      value: |
        - Full OS version: [e.g. macOS 12.0.1]
        - Docker version: (you can get it by executing `docker version`)
        - Coreum & crust git commit sha: (you can get it by executing `git rev-parse --short HEAD` in an appropriate repo)
        - Other (if applicable)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, copy and paste all necessary logs from your console.
      value: |
        <details>

        ```console
        ```

        </details>

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      value: |
        <details>

        </details>

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?
      description: Add any other context about the problem here.
      value: |
        <details>

        </details>
