// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: coreum/asset/ft/v1/params.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ParamsV1 store gov manageable parameters for v1 of the module.
type ParamsV1 struct {
	// issue_fee is the fee burnt each time new token is issued
	IssueFee types.Coin `protobuf:"bytes,1,opt,name=issue_fee,json=issueFee,proto3" json:"issue_fee" yaml:"issue_fee"`
}

func (m *ParamsV1) Reset()         { *m = ParamsV1{} }
func (m *ParamsV1) String() string { return proto.CompactTextString(m) }
func (*ParamsV1) ProtoMessage()    {}
func (*ParamsV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_b08ee2013666b045, []int{0}
}
func (m *ParamsV1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ParamsV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ParamsV1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ParamsV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamsV1.Merge(m, src)
}
func (m *ParamsV1) XXX_Size() int {
	return m.Size()
}
func (m *ParamsV1) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamsV1.DiscardUnknown(m)
}

var xxx_messageInfo_ParamsV1 proto.InternalMessageInfo

func (m *ParamsV1) GetIssueFee() types.Coin {
	if m != nil {
		return m.IssueFee
	}
	return types.Coin{}
}

// Params store gov manageable parameters.
type Params struct {
	// issue_fee is the fee burnt each time new token is issued
	IssueFee types.Coin `protobuf:"bytes,1,opt,name=issue_fee,json=issueFee,proto3" json:"issue_fee" yaml:"issue_fee"`
	// ibc_decision_timeout defines the end of the decision period for enabling IBC
	TokenUpgradeDecisionTimeout time.Time `protobuf:"bytes,2,opt,name=token_upgrade_decision_timeout,json=tokenUpgradeDecisionTimeout,proto3,stdtime" json:"token_upgrade_decision_timeout" yaml:"token_upgrade_decision_timeout"`
	// ibc_grace_period defines the period after which IBC is effectively enabled
	TokenUpgradeGracePeriod time.Duration `protobuf:"bytes,3,opt,name=token_upgrade_grace_period,json=tokenUpgradeGracePeriod,proto3,stdduration" json:"token_upgrade_grace_period" yaml:"token_upgrade_grace_period"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b08ee2013666b045, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetIssueFee() types.Coin {
	if m != nil {
		return m.IssueFee
	}
	return types.Coin{}
}

func (m *Params) GetTokenUpgradeDecisionTimeout() time.Time {
	if m != nil {
		return m.TokenUpgradeDecisionTimeout
	}
	return time.Time{}
}

func (m *Params) GetTokenUpgradeGracePeriod() time.Duration {
	if m != nil {
		return m.TokenUpgradeGracePeriod
	}
	return 0
}

func init() {
	proto.RegisterType((*ParamsV1)(nil), "coreum.asset.ft.v1.ParamsV1")
	proto.RegisterType((*Params)(nil), "coreum.asset.ft.v1.Params")
}

func init() { proto.RegisterFile("coreum/asset/ft/v1/params.proto", fileDescriptor_b08ee2013666b045) }

var fileDescriptor_b08ee2013666b045 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x6b, 0xd5, 0x40,
	0x10, 0xc7, 0xb3, 0x15, 0x4a, 0x8d, 0x17, 0x09, 0x82, 0x31, 0xc2, 0x46, 0x03, 0x82, 0x17, 0x77,
	0x89, 0xbd, 0x79, 0x4c, 0x4b, 0x3d, 0x09, 0x8f, 0x52, 0x3d, 0x88, 0x10, 0x36, 0xc9, 0x24, 0x2e,
	0x36, 0x99, 0x90, 0xdd, 0x7d, 0xd8, 0x0f, 0xe0, 0xbd, 0x78, 0xf2, 0x23, 0xf5, 0xd8, 0xa3, 0xa7,
	0x2a, 0xef, 0x7d, 0x03, 0x2f, 0x5e, 0x25, 0xbb, 0xfb, 0xb4, 0x3e, 0xc4, 0x53, 0x6f, 0x13, 0xfe,
	0xbf, 0xf9, 0xcf, 0x3f, 0xb3, 0x13, 0xa6, 0x35, 0x4e, 0x60, 0x7a, 0x2e, 0x94, 0x02, 0xcd, 0x5b,
	0xcd, 0x97, 0x39, 0x1f, 0xc5, 0x24, 0x7a, 0xc5, 0xc6, 0x09, 0x35, 0x46, 0x91, 0x03, 0x98, 0x05,
	0x58, 0xab, 0xd9, 0x32, 0x4f, 0xee, 0x75, 0xd8, 0xa1, 0x95, 0xf9, 0x5c, 0x39, 0x32, 0x49, 0x3b,
	0xc4, 0xee, 0x14, 0xb8, 0xfd, 0xaa, 0x4c, 0xcb, 0xb5, 0xec, 0x41, 0x69, 0xd1, 0x8f, 0x1e, 0xa0,
	0xdb, 0x40, 0x63, 0x26, 0xa1, 0x25, 0x0e, 0x1b, 0xbd, 0x46, 0xd5, 0xa3, 0xe2, 0x95, 0x50, 0xc0,
	0x97, 0x79, 0x05, 0x5a, 0xe4, 0xbc, 0x46, 0xe9, 0xf5, 0xec, 0x5d, 0xb8, 0xb7, 0xb0, 0xd1, 0xde,
	0xe4, 0xd1, 0x22, 0xbc, 0x2d, 0x95, 0x32, 0x50, 0xb6, 0x00, 0x31, 0x79, 0x44, 0x9e, 0xde, 0x79,
	0xfe, 0x80, 0xb9, 0x7e, 0x36, 0xf7, 0x33, 0xdf, 0xcf, 0x0e, 0x50, 0x0e, 0x45, 0x7c, 0x71, 0x95,
	0x06, 0x3f, 0xae, 0xd2, 0xbb, 0x67, 0xa2, 0x3f, 0x7d, 0x91, 0xfd, 0xee, 0xcc, 0x8e, 0xf7, 0x6c,
	0x7d, 0x04, 0x90, 0xfd, 0xdc, 0x09, 0x77, 0x9d, 0xfd, 0xcd, 0x9b, 0x47, 0x9f, 0x49, 0x48, 0x35,
	0x7e, 0x80, 0xa1, 0x34, 0x63, 0x37, 0x89, 0x06, 0xca, 0x06, 0x6a, 0xa9, 0x24, 0x0e, 0xe5, 0xbc,
	0x25, 0x34, 0x3a, 0xde, 0xb1, 0x73, 0x12, 0xe6, 0x96, 0xc4, 0x36, 0x4b, 0x62, 0x27, 0x9b, 0x2d,
	0x16, 0xb9, 0x1f, 0xf4, 0xc4, 0x0d, 0xfa, 0xbf, 0x5f, 0x76, 0xfe, 0x2d, 0x25, 0xc7, 0x0f, 0x2d,
	0xf4, 0xda, 0x31, 0x87, 0x1e, 0x39, 0x71, 0x44, 0xf4, 0x89, 0x84, 0xc9, 0xdf, 0x26, 0xdd, 0x24,
	0x6a, 0x28, 0x47, 0x98, 0x24, 0x36, 0xf1, 0x2d, 0xff, 0xe3, 0xdb, 0x81, 0x0e, 0xfd, 0xab, 0x15,
	0xcf, 0x7c, 0x9e, 0xc7, 0xff, 0xca, 0x73, 0xdd, 0x2a, 0xfb, 0x32, 0x67, 0xb9, 0x7f, 0x3d, 0xcb,
	0xcb, 0x59, 0x5e, 0x58, 0xb5, 0x78, 0x75, 0xb1, 0xa2, 0xe4, 0x72, 0x45, 0xc9, 0xf7, 0x15, 0x25,
	0xe7, 0x6b, 0x1a, 0x5c, 0xae, 0x69, 0xf0, 0x75, 0x4d, 0x83, 0xb7, 0xfb, 0x9d, 0xd4, 0xef, 0x4d,
	0xc5, 0x6a, 0xec, 0xf9, 0x81, 0xbd, 0xc3, 0x23, 0x34, 0x43, 0x63, 0xc7, 0x73, 0x7f, 0xb9, 0x1f,
	0xff, 0xdc, 0xae, 0x3e, 0x1b, 0x41, 0x55, 0xbb, 0x36, 0xe9, 0xfe, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x01, 0xb4, 0x52, 0xec, 0xdb, 0x02, 0x00, 0x00,
}

func (m *ParamsV1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ParamsV1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ParamsV1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.IssueFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.TokenUpgradeGracePeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.TokenUpgradeGracePeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.TokenUpgradeDecisionTimeout, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.TokenUpgradeDecisionTimeout):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x12
	{
		size, err := m.IssueFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ParamsV1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.IssueFee.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.IssueFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.TokenUpgradeDecisionTimeout)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.TokenUpgradeGracePeriod)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ParamsV1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ParamsV1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ParamsV1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssueFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IssueFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssueFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IssueFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenUpgradeDecisionTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.TokenUpgradeDecisionTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenUpgradeGracePeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.TokenUpgradeGracePeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
