# This file is used by `ignite chain serve` command. It will be removed once we configure and start chains
# ourselves. We won't use `ignite` to do that because it's still slow and generates a lot of mess.

accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
