name: check markdown links
on:
  push:
    branches: [master, release-v4]
  pull_request:
    branches: [master, release-v4]
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          folder-path: "./"
          check-modified-files-only: 'yes'
