name: Proto docs diff check

on:
  push:

jobs:
  proto-docs-diff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout crust
        uses: actions/checkout@v3
        with:
          repository: CoreumFoundation/crust
          path: crust
      - name: Set up crust
        run: echo "$(pwd)/crust/bin" >> $GITHUB_PATH
      # FIXME crust tidy doesn't work, that's why I added manual installation as a temp solution
      - name: install deps
        run: go mod tidy
      - name: Generate proto docs
        run: crust proto/coreum --log-format=yaml
      - name: check git diff
        run: |
          git diff --quiet "docs/api.md"
          if [ $? -eq 0 ]; then
            echo "No changes detected in docs/api.md."
            exit 0
          else
            echo "Changes detected in docs/api.md."
            exit 1
          fi
