name: Protobuf
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  breaking-change:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/CoreumFoundation/coreum.git#branch=master'
